# This file was generated by GoReleaser. DO NOT EDIT.
cask "jfmt" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "6f85dc2145c9d6e7251d29a8f06d8cffa6ec2ca67609936ce379fd2ddf4d2a51"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "746825862ac72e69dc6e4c271e783146dcaaad941ba3e373e0d9515fa2deff41"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec887a502126221372917afede9cdf71515222b95d034614ebb622614d4f5cfe"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bfe9b6d0a632f46816c7ef1488c3c47a462bbfecd4233be7038f8ddcbd77c9f2"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jfmt"
  desc "A JSON formatter and validator for the command line."
  homepage "https://github.com/krzysztofgb/jfmt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jfmt"

  # No zap stanza required

end
