# This file was generated by GoReleaser. DO NOT EDIT.
cask "jfmt" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "71b1a3ac55eb2cd9a6fa8c314c3c3912539e9e581f4c6b926b8c355009910023"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3e7d0946b4794e4290adaafb5f7374f41714c50d9a028301f9d5e0a8927d3eb9"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9addf9b3e281223a0ea917ea0c0b55ae6ba2171478791eff084863fe31780f42"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a460ac2323972680e3f0a39581a2e056aab32f170bb1e5b7dd124a9bfcb27bc"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jfmt"
  desc "A JSON formatter and validator for the command line."
  homepage "https://github.com/krzysztofgb/jfmt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jfmt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jfmt"]
    end
  end

  # No zap stanza required

end
