# This file was generated by GoReleaser. DO NOT EDIT.
cask "jfmt" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "9dc7b291825bdca49608880de67f8a983dabe042a88db00984e79b3a4c6f411a"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "119ee7fd23a96bf8b9117e10d021449b0980ea72d5f2a1da423a03b2a446fcd8"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7ce8f676a3eeeb494d5d7d8100156ee433340ec5f3cf353c0c54f8a1c128f644"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b04427f361259f124691ba3218daff5808eced8b922946271bcf1882039a4f88"
      url "https://github.com/krzysztofgb/jfmt/releases/download/v#{version}/jfmt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "jfmt"
  desc "A JSON formatter and validator for the command line."
  homepage "https://github.com/krzysztofgb/jfmt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jfmt"
  bash_completion "completions/jfmt.bash"
  fish_completion "completions/jfmt.fish"
  zsh_completion "completions/_jfmt"

  # No zap stanza required

  caveats <<~EOS
    Shell completions have been installed. If tab completion is not working,
    ensure your shell is configured to load Homebrew completions.
  EOS
end
